#userhdlbuild=visible
# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.runs/synth_1/SasquatchTopTemplate.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}

proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    } elseif { [info exist ::env(HOST)] } {
      set host $::env(HOST)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
OPTRACE "impl_1" END { }
}

######################################
# SYNTHESIS
######################################

OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcvu11p-flgb2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.cache/wt [current_project]
set_property parent.project_path C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set src_rc [catch { 
  puts "source ../TCL/PreSynthesize.tcl"
  source ../TCL/PreSynthesize.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 status "$_RESULT"
  send_msg_id runtcl-2 status "sourcing script ../TCL/PreSynthesize.tcl failed"
  return -code error
}
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgNiUtilities.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DFlop.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DFlopAsync.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DFlopUnsigned.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgCommunicationInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/lvgen/PkgCommIntConfiguration.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgNiDmaConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgXReg.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgBaggageRegTypeRegMap.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgNiDmaRegMap.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgNiDma.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcMasterPort.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommunicationInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcStreamStates.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortDataPackingFifo.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortDmaFifos.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcArbiter.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortStrmArbiterRoundRobin.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcInputArbiter.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcInputController.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcInputDataControl.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortInputDataToDmaDelay.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcInputDataControl.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcRegs.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcRegisters.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSourceStreamStateController.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcInputStream.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgAttributes.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DoubleSyncAsyncInBase.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DoubleSyncBase.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DoubleSyncSL.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcIrqInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcMasterReadInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcMasterWriteInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcOutputArbiter.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcOutputController.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSinkStreamStateController.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcOutputStream.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSinkDataControl.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSinkStreamDataReceiver.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSinkStreamTcrUpdateController.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortCommIfcSinkStream.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortDmaFifosFlatTypes.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortCommIfcMasterPortFlatTypes.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DmaPortFixedDmaCommunicationInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DoubleSyncBool.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDram2DP.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDram2DPConstants.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/GenDataValid.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/SingleClkFifoFlags.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DualPortRAM_Vivado.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/DualPortRAM.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/SingleClkFifo.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/SingleClockDeviceRam.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/Dram2DP.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/packages/PkgBaRegPortConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgBaRegPort.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgChinch.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgChinchConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgSwitchedChinch.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgDmaPortRecordFlattening.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/lvgen/PkgLvFpgaConst.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgFlexRioAxiStream.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fixedlogic/sasquatchfixedlogic/vhdl/FixedLogicWrapper.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgInstructionFifoConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgInstructionFifo.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgLinkStorageRamConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgLinkStorageRam.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PkgInchwormWrapper.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/LinkStorageRamAddrMapper.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/LinkStorageRamXilinx.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PcieUspG3x8TandemGtyInchwormWrapper.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/IwCompanion.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/MacallanIFifo.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/G3UspGtyHostInterface.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/IoRefClkSelect.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/iotargetconfig/vhdl/sasquatch/PkgFlexRioTargetConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/packages/PkgSasquatch.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fixedlogic/sasquatchfixedlogic/vhdl/Packages/PkgSysMonConfig.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/dram/sasquatch/vhdl/SasquatchDramWrapper.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/dram/sasquatch/vhdl/SasquatchBank0Dram.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/dram/sasquatch/vhdl/SasquatchBank1Dram.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/dram/sasquatch/vhdl/SasquatchEmptyDram.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/dram/sasquatch/vhdl/SasquatchDram.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/SasquatchIoBuffers.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/common/vhdl/SasquatchIoBuffersStage1.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/vhdl/lvgen/TheWindow.vhd
  C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/vhdl/SasquatchTopTemplate.vhd
}
read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/MacallanFixedLogic.edf
read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/MacallanIFifoN.edf
read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/IwCompanionN.edf
read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PcieUspG3x8TandemGtyInchwormNetlist.edf
read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PxieUspTimingEngine.edf
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/Dram2DP.xdc
set_property used_in_implementation false [get_files C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/Dram2DP.xdc]

read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints.xdc
set_property used_in_implementation false [get_files C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints.xdc]

read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints_place.xdc
set_property used_in_implementation false [get_files C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints_place.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top SasquatchTopTemplate -part xcvu11p-flgb2104-2-e -flatten_hierarchy full -keep_equivalent_registers
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SasquatchTopTemplate.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SasquatchTopTemplate_utilization_synth.rpt -pb SasquatchTopTemplate_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }


######################################
# IMPLEMENTATION
######################################

OPTRACE "impl_1" START { ROLLUP_1 }
OPTRACE "Phase: Init Design" START { ROLLUP_AUTO }
start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 5
OPTRACE "create in-memory project" START { }
  create_project -in_memory -part xcvu11p-flgb2104-2-e
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
OPTRACE "create in-memory project" END { }
OPTRACE "set parameters" START { }
  set_property webtalk.parent_dir C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.cache/wt [current_project]
  set_property parent.project_path C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.xpr [current_project]
  set_property ip_output_repo C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES XPM_MEMORY [current_project]
OPTRACE "set parameters" END { }
OPTRACE "add files" START { }
  add_files -quiet C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/VivadoProject/MySasquatchProj.runs/synth_1/SasquatchTopTemplate.dcp
  read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/MacallanFixedLogic.edf
  read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/MacallanIFifoN.edf
  read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/IwCompanionN.edf
  read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PcieUspG3x8TandemGtyInchwormNetlist.edf
  read_edif C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/objects/gathereddeps/PxieUspTimingEngine.edf
OPTRACE "read constraints: implementation" START { }
  read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/Dram2DP.xdc
  read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints.xdc
  read_xdc C:/dev/git/hw-flexrio/baseboards/fpgas/source/fpga/pxie-7903/xdc/constraints_place.xdc
OPTRACE "read constraints: implementation" END { }
OPTRACE "add files" END { }
OPTRACE "link_design" START { }
  link_design -top SasquatchTopTemplate -part xcvu11p-flgb2104-2-e
OPTRACE "link_design" END { }
OPTRACE "gray box cells" START { }
OPTRACE "gray box cells" END { }
OPTRACE "init_design_reports" START { REPORT }
OPTRACE "init_design_reports" END { }
OPTRACE "init_design_write_hwdef" START { }
OPTRACE "init_design_write_hwdef" END { }
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Init Design" END { }
OPTRACE "Phase: Opt Design" START { ROLLUP_AUTO }
start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
OPTRACE "read constraints: opt_design" START { }
OPTRACE "read constraints: opt_design" END { }
OPTRACE "opt_design" START { }
  opt_design -directive Explore
OPTRACE "opt_design" END { }
OPTRACE "read constraints: opt_design_post" START { }
OPTRACE "read constraints: opt_design_post" END { }
OPTRACE "Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force SasquatchTopTemplate_opt.dcp
OPTRACE "Opt Design: write_checkpoint" END { }
OPTRACE "opt_design reports" START { REPORT }
  create_report "impl_1_opt_report_drc_0" "report_drc -file SasquatchTopTemplate_drc_opted.rpt -pb SasquatchTopTemplate_drc_opted.pb -rpx SasquatchTopTemplate_drc_opted.rpx"
OPTRACE "opt_design reports" END { }
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Opt Design" END { }
OPTRACE "Phase: Place Design" START { ROLLUP_AUTO }
start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
OPTRACE "read constraints: place_design" START { }
OPTRACE "read constraints: place_design" END { }
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
OPTRACE "implement_debug_core" START { }
    implement_debug_core 
OPTRACE "implement_debug_core" END { }
  } 
OPTRACE "place_design" START { }
  place_design -directive Explore
OPTRACE "place_design" END { }
OPTRACE "read constraints: place_design_post" START { }
OPTRACE "read constraints: place_design_post" END { }
OPTRACE "Place Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force SasquatchTopTemplate_placed.dcp
OPTRACE "Place Design: write_checkpoint" END { }
OPTRACE "place_design reports" START { REPORT }
  create_report "impl_1_place_report_io_0" "report_io -file SasquatchTopTemplate_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file SasquatchTopTemplate_utilization_placed.rpt -pb SasquatchTopTemplate_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file SasquatchTopTemplate_control_sets_placed.rpt"
OPTRACE "place_design reports" END { }
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Place Design" END { }
OPTRACE "Phase: Physical Opt Design" START { ROLLUP_AUTO }
start_step phys_opt_design
set ACTIVE_STEP phys_opt_design
set rc [catch {
  create_msg_db phys_opt_design.pb
OPTRACE "read constraints: phys_opt_design" START { }
OPTRACE "read constraints: phys_opt_design" END { }
OPTRACE "phys_opt_design" START { }
  phys_opt_design -directive Explore
OPTRACE "phys_opt_design" END { }
OPTRACE "read constraints: phys_opt_design_post" START { }
OPTRACE "read constraints: phys_opt_design_post" END { }
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force SasquatchTopTemplate_physopt.dcp
OPTRACE "Post-Place Phys Opt Design: write_checkpoint" END { }
OPTRACE "phys_opt_design report" START { REPORT }
OPTRACE "phys_opt_design report" END { }
  close_msg_db -file phys_opt_design.pb
} RESULT]
if {$rc} {
  step_failed phys_opt_design
  return -code error $RESULT
} else {
  end_step phys_opt_design
  unset ACTIVE_STEP 
}

OPTRACE "Phase: Physical Opt Design" END { }
OPTRACE "Phase: Route Design" START { ROLLUP_AUTO }
start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
OPTRACE "read constraints: route_design" START { }
OPTRACE "read constraints: route_design" END { }
OPTRACE "route_design" START { }
  route_design -directive Explore
OPTRACE "route_design" END { }
OPTRACE "read constraints: route_design_post" START { }
OPTRACE "read constraints: route_design_post" END { }
OPTRACE "Route Design: write_checkpoint" START { CHECKPOINT }
  write_checkpoint -force SasquatchTopTemplate_routed.dcp
OPTRACE "Route Design: write_checkpoint" END { }
OPTRACE "route_design reports" START { REPORT }
  create_report "impl_1_route_report_drc_0" "report_drc -file SasquatchTopTemplate_drc_routed.rpt -pb SasquatchTopTemplate_drc_routed.pb -rpx SasquatchTopTemplate_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file SasquatchTopTemplate_methodology_drc_routed.rpt -pb SasquatchTopTemplate_methodology_drc_routed.pb -rpx SasquatchTopTemplate_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file SasquatchTopTemplate_power_routed.rpt -pb SasquatchTopTemplate_power_summary_routed.pb -rpx SasquatchTopTemplate_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file SasquatchTopTemplate_route_status.rpt -pb SasquatchTopTemplate_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file SasquatchTopTemplate_timing_summary_routed.rpt -pb SasquatchTopTemplate_timing_summary_routed.pb -rpx SasquatchTopTemplate_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file SasquatchTopTemplate_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file SasquatchTopTemplate_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file SasquatchTopTemplate_bus_skew_routed.rpt -pb SasquatchTopTemplate_bus_skew_routed.pb -rpx SasquatchTopTemplate_bus_skew_routed.rpx"
OPTRACE "route_design reports" END { }
OPTRACE "route_design misc" START { }
  close_msg_db -file route_design.pb
OPTRACE "route_design write_checkpoint" START { CHECKPOINT }
OPTRACE "route_design write_checkpoint" END { }
} RESULT]
if {$rc} {
  write_checkpoint -force SasquatchTopTemplate_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

OPTRACE "route_design misc" END { }
OPTRACE "Phase: Route Design" END { }
OPTRACE "impl_1" END { }

exit