-------------------------------------------------------------------------------
--
-- File: PkgLvFpgaConst.vhd
-- Author: David Cabrera
-- Original Project: Puma K7
-- Date: 22 July 2013
--
-------------------------------------------------------------------------------
-- MIT License
-- 
-- Copyright (c) 2025 National Instruments Corporation
-- 
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this
-- software and associated documentation files (the "Software"), to deal in the Software
-- without restriction, including without limitation the rights to use, copy, modify, merge,
-- publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
-- to whom the Software is furnished to do so, subject to the following conditions:
-- 
-- The above copyright notice and this permission notice shall be included in all copies or
-- substantial portions of the Software.
-- 
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
-- INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
-- PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
-- FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
-- DEALINGS IN THE SOFTWARE.
-------------------------------------------------------------------------------
--
-- Purpose:
--  This file will be generated by LV FPGA to set constants required for
--  Puma K7 compilation.
--
-------------------------------------------------------------------------------
--
-- githubvisible=true

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;

package PkgLvFpgaConst is

  -----------------------------------------------------------------------------
  -- LV FPGA generated constants
  -----------------------------------------------------------------------------

  constant kExpectedTbId   : std_logic_vector(31 downto 0) := X"D00FD00F";
  constant kExpectDumbTb   : std_logic := '1';
  constant kEnableFamClockSync : std_logic := '0';
  constant kFamClockSrcSel  : std_logic := '0';
  constant kInsertBank0Mig  : boolean := false;
  constant kInsertBank1Mig  : boolean := false;
  constant kAuxDioDefaultVoltage : natural := 3300;
  constant kAuxMgtClipPresent : boolean := false;
  constant kCfgSubsysId : std_logic_vector(15 downto 0) := X"78F9";  

  -- Required for HMB
  constant kDram2DPBaseAddress : natural := 16#20000#;
  constant kInsertHostMemoryBufferMig : boolean := false;
  constant kInsertLowLatencyBufferMig : boolean := false;

end PkgLvFpgaConst;

package body PkgLvFpgaConst is

  
end PkgLvFpgaConst;

